server:
  port: 10002
user:
  userServicePath: http://192.168.137.7:10001/simple/
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://peer1:10000/eureka,http://peer2:10003/eureka
  instance:
    prefer-ip-address: true
spring:
  application:
    name: microservice-consumer-movie
